---
- name: Create a VM from scratch Ansible
  hosts: vcenter
  connection: local
  gather_facts: no
  vars_files:

    - ../../group_vars/vcenterpass.yml

  tasks:
  - name: Create a virtual machine
    vmware_guest:
        datacenter: "{{ datacenter }}"
        hostname: 192.168.136.50
        username: "{{ username }}"
        password: "{{ password }}"
        validate_certs: no
        folder: /DEV/
        name: test_vm__aju_0001
        state: poweredon
        guest_id: centos64Guest
        esxi_hostname: vmlabesxi001.labvmware.local
        disk:
        - size_gb: 10
          type: thin
          datastore: FreeNAS1
        hardware:
          memory_mb: 1024
          num_cpus: 2
          scsi: paravirtual
        cdrom:
          type: iso
          iso_path: "[FreeNAS1] ISOs/CentOS-7-x86_64-Minimal-1810.iso"
        networks:
        - name: VM Network
          mac: aa:bb:dd:aa:00:14
          ip: 192.168.136.110
          netmask: 255.255.255.0
          device_type: vmxnet3
    delegate_to: localhost
    register: deploy_vm
